CREATE TABLE PAIS (
    ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(30),
    PRIMARY KEY(ID_PAIS)
);

CREATE TABLE ESTADO (
    ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(30),
    ID_PAIS NUMBER,
    PRIMARY KEY(ID_ESTADO)
);
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY (ID_PAIS) REFERENCES PAIS;


CREATE TABLE CIDADE (
    ID_CIDADE NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(30),
    ID_ESTADO NUMBER,
    PRIMARY KEY(ID_CIDADE)
);
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO;


CREATE TABLE BAIRRO (
    ID_BAIRRO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(30),
    ID_CIDADE NUMBER,
    PRIMARY KEY(ID_BAIRRO)
);
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE;


CREATE TABLE ENDERECO (
    ID_ENDERECO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(30),
    ID_BAIRRO NUMBER,
    PRIMARY KEY(ID_ENDERECO)
);
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO;


CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(30),
    ID_ENDERECO NUMBER,
    PRIMARY KEY(ID_CLIENTE)
);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO;


--INSERINDO DADOS NA TABELA PAIS 
INSERT INTO PAIS (NOME) VALUES ('BRASIL');

INSERT INTO PAIS (NOME) VALUES ('ALEMANHA');

INSERT INTO PAIS (NOME) VALUES ('IRLANDA');

INSERT INTO PAIS (NOME) VALUES ('CANADA');

INSERT INTO PAIS (NOME) VALUES ('FRANÇA');


--INSERINDO DADOS NA TABELA ESTADO 
INSERT INTO ESTADO (NOME, ID_PAIS) VALUES ('SÃO PAULO', 1);

INSERT INTO ESTADO (NOME, ID_PAIS) VALUES ('FRANKFURT', 2);

INSERT INTO ESTADO (NOME, ID_PAIS) VALUES ('ROCHEDA', 3);

INSERT INTO ESTADO (NOME, ID_PAIS) VALUES ('VANCOUVER', 4);

INSERT INTO ESTADO (NOME, ID_PAIS) VALUES ('PARIS', 5);


--INSERINDO DADOS NA TABELA CIDADE 
INSERT INTO CIDADE (NOME, ID_ESTADO) VALUES ('TABOÃO DA SERRA', 1);

INSERT INTO CIDADE (NOME, ID_ESTADO) VALUES ('ORSTROICH', 2);

INSERT INTO CIDADE (NOME, ID_ESTADO) VALUES ('CALDIVA', 3);

INSERT INTO CIDADE (NOME, ID_ESTADO) VALUES ('RUANET', 4);

INSERT INTO CIDADE (NOME, ID_ESTADO) VALUES ('RESTRAVO', 5);


--INSERINDO DADOS NA TABELA BAIRRO 
INSERT INTO BAIRRO (NOME, ID_CIDADE) VALUES ('JARDIM JUSSARA', 1);

INSERT INTO BAIRRO (NOME, ID_CIDADE) VALUES ('LAMAR', 2);

INSERT INTO BAIRRO (NOME, ID_CIDADE) VALUES ('CAMAVINGA', 3);

INSERT INTO BAIRRO (NOME, ID_CIDADE) VALUES ('LOROIA', 4);

INSERT INTO BAIRRO (NOME, ID_CIDADE) VALUES ('YANDER', 5);


--INSERINDO DADOS NA TABELA ENDERECO 
INSERT INTO ENDERECO (NOME, ID_BAIRRO) VALUES ('AV JOSÉ PEDRO 15', 1);

INSERT INTO ENDERECO (NOME, ID_BAIRRO) VALUES ('RUA SÃO CAMILO 35', 2);

INSERT INTO ENDERECO (NOME, ID_BAIRRO) VALUES ('STREET ISABEL YARA 598', 3);

INSERT INTO ENDERECO (NOME, ID_BAIRRO) VALUES ('AV BRADESCO 1415', 4);

INSERT INTO ENDERECO (NOME, ID_BAIRRO) VALUES ('STREET NAMAKUZA', 5);


--INSERINDO DADOS NA TABELA CLIENTE 
INSERT INTO CLIENTE (NOME, ID_ENDERECO) VALUES ('RENATO', 1);

INSERT INTO CLIENTE (NOME, ID_ENDERECO) VALUES ('YURI', 2);

INSERT INTO CLIENTE (NOME, ID_ENDERECO) VALUES ('FERNANDO', 3);

INSERT INTO CLIENTE (NOME, ID_ENDERECO) VALUES ('JOSE', 4);

INSERT INTO CLIENTE (NOME, ID_ENDERECO) VALUES ('CAMILA', 5);